// 500+ kid-friendly words for Daily Word + Missing Letter activities.
// Vocabulary tuned for ages 4-7: concrete nouns, simple verbs/adjectives,
// emoji-mappable. Translations are best-effort and flagged for native-speaker
// review before any production launch.

export const DAILY_WORDS = [
  // ---------- ANIMALS (80) ----------
  { en: 'cat',      ur: 'بلی',     ar: 'قطة',    emoji: '🐱' },
  { en: 'dog',      ur: 'کتا',     ar: 'كلب',    emoji: '🐶' },
  { en: 'cow',      ur: 'گائے',     ar: 'بقرة',   emoji: '🐄' },
  { en: 'horse',    ur: 'گھوڑا',   ar: 'حصان',   emoji: '🐴' },
  { en: 'sheep',    ur: 'بھیڑ',    ar: 'خروف',   emoji: '🐑' },
  { en: 'goat',     ur: 'بکری',    ar: 'ماعز',   emoji: '🐐' },
  { en: 'pig',      ur: 'سور',     ar: 'خنزير',  emoji: '🐷' },
  { en: 'lion',     ur: 'شیر',     ar: 'أسد',    emoji: '🦁' },
  { en: 'tiger',    ur: 'چیتا',    ar: 'نمر',    emoji: '🐯' },
  { en: 'bear',     ur: 'ریچھ',    ar: 'دب',     emoji: '🐻' },
  { en: 'panda',    ur: 'پانڈا',   ar: 'باندا',  emoji: '🐼' },
  { en: 'koala',    ur: 'کوآلا',   ar: 'كوالا',  emoji: '🐨' },
  { en: 'wolf',     ur: 'بھیڑیا',  ar: 'ذئب',    emoji: '🐺' },
  { en: 'fox',      ur: 'لومڑی',   ar: 'ثعلب',   emoji: '🦊' },
  { en: 'rabbit',   ur: 'خرگوش',   ar: 'أرنب',   emoji: '🐰' },
  { en: 'mouse',    ur: 'چوہا',    ar: 'فأر',    emoji: '🐭' },
  { en: 'rat',      ur: 'چوہا',    ar: 'جرذ',    emoji: '🐀' },
  { en: 'hamster',  ur: 'ہمسٹر',   ar: 'هامستر', emoji: '🐹' },
  { en: 'squirrel', ur: 'گلہری',   ar: 'سنجاب',  emoji: '🐿️' },
  { en: 'deer',     ur: 'ہرن',     ar: 'غزال',   emoji: '🦌' },
  { en: 'elephant', ur: 'ہاتھی',   ar: 'فيل',    emoji: '🐘' },
  { en: 'giraffe',  ur: 'زرافہ',   ar: 'زرافة',  emoji: '🦒' },
  { en: 'zebra',    ur: 'زیبرا',   ar: 'حمار وحشي', emoji: '🦓' },
  { en: 'monkey',   ur: 'بندر',    ar: 'قرد',    emoji: '🐵' },
  { en: 'gorilla',  ur: 'گوریلا',  ar: 'غوريلا', emoji: '🦍' },
  { en: 'kangaroo', ur: 'کینگرو',  ar: 'كنغر',   emoji: '🦘' },
  { en: 'camel',    ur: 'اونٹ',    ar: 'جمل',    emoji: '🐪' },
  { en: 'donkey',   ur: 'گدھا',    ar: 'حمار',   emoji: '🫏' },
  { en: 'rhino',    ur: 'گینڈا',   ar: 'وحيد القرن', emoji: '🦏' },
  { en: 'hippo',    ur: 'دریائی گھوڑا', ar: 'فرس النهر', emoji: '🦛' },
  { en: 'fish',     ur: 'مچھلی',   ar: 'سمكة',   emoji: '🐟' },
  { en: 'shark',    ur: 'شارک',    ar: 'قرش',    emoji: '🦈' },
  { en: 'whale',    ur: 'وہیل',    ar: 'حوت',    emoji: '🐳' },
  { en: 'dolphin',  ur: 'ڈولفن',   ar: 'دلفين',  emoji: '🐬' },
  { en: 'octopus',  ur: 'آکٹوپس',  ar: 'أخطبوط', emoji: '🐙' },
  { en: 'crab',     ur: 'کیکڑا',   ar: 'سرطان',  emoji: '🦀' },
  { en: 'lobster',  ur: 'لابسٹر',  ar: 'كركند',  emoji: '🦞' },
  { en: 'shrimp',   ur: 'جھینگا',  ar: 'جمبري',  emoji: '🦐' },
  { en: 'turtle',   ur: 'کچھوا',   ar: 'سلحفاة', emoji: '🐢' },
  { en: 'snake',    ur: 'سانپ',    ar: 'ثعبان',  emoji: '🐍' },
  { en: 'frog',     ur: 'مینڈک',   ar: 'ضفدع',   emoji: '🐸' },
  { en: 'lizard',   ur: 'چھپکلی',  ar: 'سحلية',  emoji: '🦎' },
  { en: 'crocodile', ur: 'مگرمچھ', ar: 'تمساح',  emoji: '🐊' },
  { en: 'bird',     ur: 'پرندہ',   ar: 'طائر',   emoji: '🐦' },
  { en: 'parrot',   ur: 'طوطا',    ar: 'ببغاء',  emoji: '🦜' },
  { en: 'eagle',    ur: 'عقاب',    ar: 'نسر',    emoji: '🦅' },
  { en: 'owl',      ur: 'الو',     ar: 'بومة',   emoji: '🦉' },
  { en: 'duck',     ur: 'بطخ',     ar: 'بطة',    emoji: '🦆' },
  { en: 'swan',     ur: 'ہنس',     ar: 'بجعة',   emoji: '🦢' },
  { en: 'chicken',  ur: 'مرغی',    ar: 'دجاجة',  emoji: '🐔' },
  { en: 'rooster',  ur: 'مرغا',    ar: 'ديك',    emoji: '🐓' },
  { en: 'chick',    ur: 'چوزہ',    ar: 'كتكوت',  emoji: '🐤' },
  { en: 'penguin',  ur: 'پینگوئن', ar: 'بطريق',  emoji: '🐧' },
  { en: 'turkey',   ur: 'ٹرکی',    ar: 'ديك رومي', emoji: '🦃' },
  { en: 'peacock',  ur: 'مور',     ar: 'طاووس',  emoji: '🦚' },
  { en: 'flamingo', ur: 'فلیمنگو', ar: 'فلامنغو', emoji: '🦩' },
  { en: 'dove',     ur: 'فاختہ',   ar: 'حمامة',  emoji: '🕊️' },
  { en: 'bee',      ur: 'مکھی',    ar: 'نحلة',   emoji: '🐝' },
  { en: 'butterfly', ur: 'تتلی',   ar: 'فراشة',  emoji: '🦋' },
  { en: 'ant',      ur: 'چیونٹی',  ar: 'نملة',   emoji: '🐜' },
  { en: 'spider',   ur: 'مکڑی',    ar: 'عنكبوت', emoji: '🕷️' },
  { en: 'snail',    ur: 'گھونگھا', ar: 'حلزون',  emoji: '🐌' },
  { en: 'worm',     ur: 'کیڑا',    ar: 'دودة',   emoji: '🪱' },
  { en: 'beetle',   ur: 'بھنورا',  ar: 'خنفساء', emoji: '🪲' },
  { en: 'cricket',  ur: 'جھینگر',  ar: 'صرصور',  emoji: '🦗' },
  { en: 'dragon',   ur: 'اژدہا',   ar: 'تنين',   emoji: '🐉' },
  { en: 'unicorn',  ur: 'یونیکورن', ar: 'يونيكورن', emoji: '🦄' },
  { en: 'dinosaur', ur: 'ڈائناسور', ar: 'ديناصور', emoji: '🦕' },
  { en: 'bat',      ur: 'چمگادڑ',  ar: 'خفاش',   emoji: '🦇' },
  { en: 'bug',      ur: 'کیڑا',    ar: 'حشرة',   emoji: '🐞' },
  { en: 'pony',     ur: 'ٹٹو',     ar: 'مهر',    emoji: '🐎' },
  { en: 'puppy',    ur: 'پلا',     ar: 'جرو',    emoji: '🐕' },
  { en: 'kitten',   ur: 'بلی کا بچہ', ar: 'هريرة', emoji: '🐈' },
  { en: 'lamb',     ur: 'برّہ',    ar: 'حمل',    emoji: '🐑' },
  { en: 'foal',     ur: 'بچھیرا',  ar: 'مهر',    emoji: '🐴' },
  { en: 'calf',     ur: 'بچھڑا',   ar: 'عجل',    emoji: '🐄' },
  { en: 'jellyfish', ur: 'جیلی فش', ar: 'قنديل البحر', emoji: '🪼' },
  { en: 'starfish', ur: 'سٹار فش', ar: 'نجم البحر', emoji: '⭐' },
  { en: 'seal',     ur: 'سیل',     ar: 'فقمة',   emoji: '🦭' },
  { en: 'walrus',   ur: 'والرس',   ar: 'فظ',     emoji: '🦭' },

  // ---------- FOOD / FRUIT / DRINK (80) ----------
  { en: 'apple',    ur: 'سیب',     ar: 'تفاحة',  emoji: '🍎' },
  { en: 'banana',   ur: 'کیلا',    ar: 'موز',    emoji: '🍌' },
  { en: 'orange',   ur: 'مالٹا',   ar: 'برتقال', emoji: '🍊' },
  { en: 'grapes',   ur: 'انگور',   ar: 'عنب',    emoji: '🍇' },
  { en: 'mango',    ur: 'آم',      ar: 'مانجو',  emoji: '🥭' },
  { en: 'lemon',    ur: 'لیموں',   ar: 'ليمون',  emoji: '🍋' },
  { en: 'pear',     ur: 'ناشپاتی', ar: 'كمثرى',  emoji: '🍐' },
  { en: 'peach',    ur: 'آڑو',     ar: 'خوخ',    emoji: '🍑' },
  { en: 'plum',     ur: 'آلو بخارا', ar: 'برقوق', emoji: '🍑' },
  { en: 'cherry',   ur: 'چیری',    ar: 'كرز',    emoji: '🍒' },
  { en: 'strawberry', ur: 'اسٹرابیری', ar: 'فراولة', emoji: '🍓' },
  { en: 'blueberry', ur: 'بلیوبیری', ar: 'توت أزرق', emoji: '🫐' },
  { en: 'kiwi',     ur: 'کیوی',    ar: 'كيوي',   emoji: '🥝' },
  { en: 'pineapple', ur: 'انناس',  ar: 'أناناس', emoji: '🍍' },
  { en: 'watermelon', ur: 'تربوز', ar: 'بطيخ',   emoji: '🍉' },
  { en: 'melon',    ur: 'خربوزہ',  ar: 'شمام',   emoji: '🍈' },
  { en: 'coconut',  ur: 'ناریل',   ar: 'جوز الهند', emoji: '🥥' },
  { en: 'avocado',  ur: 'ایوکاڈو', ar: 'أفوكادو', emoji: '🥑' },
  { en: 'tomato',   ur: 'ٹماٹر',   ar: 'طماطم',  emoji: '🍅' },
  { en: 'potato',   ur: 'آلو',     ar: 'بطاطس',  emoji: '🥔' },
  { en: 'carrot',   ur: 'گاجر',    ar: 'جزر',    emoji: '🥕' },
  { en: 'corn',     ur: 'مکئی',    ar: 'ذرة',    emoji: '🌽' },
  { en: 'pepper',   ur: 'مرچ',     ar: 'فلفل',   emoji: '🌶️' },
  { en: 'cucumber', ur: 'کھیرا',   ar: 'خيار',   emoji: '🥒' },
  { en: 'broccoli', ur: 'بروکلی',  ar: 'بروكلي', emoji: '🥦' },
  { en: 'onion',    ur: 'پیاز',    ar: 'بصل',    emoji: '🧅' },
  { en: 'garlic',   ur: 'لہسن',    ar: 'ثوم',    emoji: '🧄' },
  { en: 'mushroom', ur: 'کھمبی',   ar: 'فطر',    emoji: '🍄' },
  { en: 'eggplant', ur: 'بینگن',   ar: 'باذنجان', emoji: '🍆' },
  { en: 'lettuce',  ur: 'سلاد پتہ', ar: 'خس',    emoji: '🥬' },
  { en: 'bread',    ur: 'روٹی',    ar: 'خبز',    emoji: '🍞' },
  { en: 'rice',     ur: 'چاول',    ar: 'أرز',    emoji: '🍚' },
  { en: 'pasta',    ur: 'پاستا',   ar: 'باستا',  emoji: '🍝' },
  { en: 'noodles',  ur: 'نوڈلز',   ar: 'نودلز',  emoji: '🍜' },
  { en: 'pizza',    ur: 'پیزا',    ar: 'بيتزا',  emoji: '🍕' },
  { en: 'burger',   ur: 'برگر',    ar: 'برغر',   emoji: '🍔' },
  { en: 'fries',    ur: 'چپس',     ar: 'بطاطا مقلية', emoji: '🍟' },
  { en: 'sandwich', ur: 'سینڈوچ',  ar: 'شطيرة',  emoji: '🥪' },
  { en: 'taco',     ur: 'ٹیکو',    ar: 'تاكو',   emoji: '🌮' },
  { en: 'sushi',    ur: 'سشی',     ar: 'سوشي',   emoji: '🍣' },
  { en: 'cheese',   ur: 'پنیر',    ar: 'جبن',    emoji: '🧀' },
  { en: 'butter',   ur: 'مکھن',    ar: 'زبدة',   emoji: '🧈' },
  { en: 'milk',     ur: 'دودھ',    ar: 'حليب',   emoji: '🥛' },
  { en: 'water',    ur: 'پانی',    ar: 'ماء',    emoji: '💧' },
  { en: 'juice',    ur: 'جوس',     ar: 'عصير',   emoji: '🧃' },
  { en: 'tea',      ur: 'چائے',    ar: 'شاي',    emoji: '🍵' },
  { en: 'coffee',   ur: 'کافی',    ar: 'قهوة',   emoji: '☕' },
  { en: 'soup',     ur: 'سوپ',     ar: 'حساء',   emoji: '🍲' },
  { en: 'salad',    ur: 'سلاد',    ar: 'سلطة',   emoji: '🥗' },
  { en: 'egg',      ur: 'انڈا',    ar: 'بيضة',   emoji: '🥚' },
  { en: 'chicken',  ur: 'مرغ',     ar: 'دجاج',   emoji: '🍗' },
  { en: 'meat',     ur: 'گوشت',    ar: 'لحم',    emoji: '🥩' },
  { en: 'bacon',    ur: 'بیکن',    ar: 'لحم مقدد', emoji: '🥓' },
  { en: 'cake',     ur: 'کیک',     ar: 'كعكة',   emoji: '🍰' },
  { en: 'cookie',   ur: 'بسکٹ',    ar: 'بسكويت', emoji: '🍪' },
  { en: 'donut',    ur: 'ڈونٹ',    ar: 'دونات',  emoji: '🍩' },
  { en: 'candy',    ur: 'ٹافی',    ar: 'حلوى',   emoji: '🍬' },
  { en: 'lollipop', ur: 'لالی پاپ', ar: 'مصاصة', emoji: '🍭' },
  { en: 'chocolate', ur: 'چاکلیٹ', ar: 'شوكولاتة', emoji: '🍫' },
  { en: 'icecream', ur: 'آئس کریم', ar: 'مثلجات', emoji: '🍦' },
  { en: 'pie',      ur: 'پائی',    ar: 'فطيرة',  emoji: '🥧' },
  { en: 'pancake',  ur: 'پین کیک', ar: 'فطيرة محلاة', emoji: '🥞' },
  { en: 'waffle',   ur: 'وافل',    ar: 'وافل',   emoji: '🧇' },
  { en: 'bagel',    ur: 'بیگل',    ar: 'بيغل',   emoji: '🥯' },
  { en: 'croissant', ur: 'کروسانٹ', ar: 'كرواسون', emoji: '🥐' },
  { en: 'pretzel',  ur: 'پریٹزل',  ar: 'بريتزل', emoji: '🥨' },
  { en: 'popcorn',  ur: 'پاپ کارن', ar: 'فشار',  emoji: '🍿' },
  { en: 'honey',    ur: 'شہد',     ar: 'عسل',    emoji: '🍯' },
  { en: 'jam',      ur: 'جام',     ar: 'مربى',   emoji: '🍯' },
  { en: 'salt',     ur: 'نمک',     ar: 'ملح',    emoji: '🧂' },
  { en: 'sugar',    ur: 'چینی',    ar: 'سكر',    emoji: '🍬' },
  { en: 'soda',     ur: 'سوڈا',    ar: 'صودا',   emoji: '🥤' },
  { en: 'cup',      ur: 'کپ',      ar: 'كوب',    emoji: '🥤' },
  { en: 'bottle',   ur: 'بوتل',    ar: 'زجاجة',  emoji: '🍼' },
  { en: 'fig',      ur: 'انجیر',   ar: 'تين',    emoji: '🍑' },
  { en: 'date',     ur: 'کھجور',   ar: 'تمر',    emoji: '🌴' },
  { en: 'olive',    ur: 'زیتون',   ar: 'زيتون',  emoji: '🫒' },
  { en: 'nut',      ur: 'گری',     ar: 'مكسرات', emoji: '🥜' },
  { en: 'pea',      ur: 'مٹر',     ar: 'بازلاء', emoji: '🟢' },
  { en: 'bean',     ur: 'لوبیا',   ar: 'فاصوليا', emoji: '🫘' },
  { en: 'oat',      ur: 'جئی',     ar: 'شوفان',  emoji: '🌾' },

  // ---------- BODY (30) ----------
  { en: 'eye',      ur: 'آنکھ',    ar: 'عين',    emoji: '👁️' },
  { en: 'ear',      ur: 'کان',     ar: 'أذن',    emoji: '👂' },
  { en: 'nose',     ur: 'ناک',     ar: 'أنف',    emoji: '👃' },
  { en: 'mouth',    ur: 'منہ',     ar: 'فم',     emoji: '👄' },
  { en: 'tongue',   ur: 'زبان',    ar: 'لسان',   emoji: '👅' },
  { en: 'tooth',    ur: 'دانت',    ar: 'سن',     emoji: '🦷' },
  { en: 'lip',      ur: 'ہونٹ',    ar: 'شفة',    emoji: '👄' },
  { en: 'face',     ur: 'چہرہ',    ar: 'وجه',    emoji: '😀' },
  { en: 'head',     ur: 'سر',      ar: 'رأس',    emoji: '👤' },
  { en: 'hair',     ur: 'بال',     ar: 'شعر',    emoji: '💇' },
  { en: 'hand',     ur: 'ہاتھ',    ar: 'يد',     emoji: '✋' },
  { en: 'foot',     ur: 'پاؤں',    ar: 'قدم',    emoji: '🦶' },
  { en: 'arm',      ur: 'بازو',    ar: 'ذراع',   emoji: '💪' },
  { en: 'leg',      ur: 'ٹانگ',    ar: 'ساق',    emoji: '🦵' },
  { en: 'finger',   ur: 'انگلی',   ar: 'إصبع',   emoji: '☝️' },
  { en: 'thumb',    ur: 'انگوٹھا', ar: 'إبهام',  emoji: '👍' },
  { en: 'toe',      ur: 'انگوٹھا', ar: 'إصبع القدم', emoji: '🦶' },
  { en: 'knee',     ur: 'گھٹنا',   ar: 'ركبة',   emoji: '🦵' },
  { en: 'elbow',    ur: 'کہنی',    ar: 'كوع',    emoji: '💪' },
  { en: 'shoulder', ur: 'کندھا',   ar: 'كتف',    emoji: '🤷' },
  { en: 'back',     ur: 'پیٹھ',    ar: 'ظهر',    emoji: '🔙' },
  { en: 'neck',     ur: 'گردن',    ar: 'رقبة',   emoji: '👤' },
  { en: 'chest',    ur: 'سینہ',    ar: 'صدر',    emoji: '👤' },
  { en: 'belly',    ur: 'پیٹ',     ar: 'بطن',    emoji: '🤰' },
  { en: 'heart',    ur: 'دل',      ar: 'قلب',    emoji: '❤️' },
  { en: 'brain',    ur: 'دماغ',    ar: 'دماغ',   emoji: '🧠' },
  { en: 'bone',     ur: 'ہڈی',     ar: 'عظم',    emoji: '🦴' },
  { en: 'skin',     ur: 'جلد',     ar: 'جلد',    emoji: '🫳' },
  { en: 'cheek',    ur: 'گال',     ar: 'خد',     emoji: '😊' },
  { en: 'chin',     ur: 'ٹھوڑی',   ar: 'ذقن',    emoji: '😀' },

  // ---------- COLORS (15) ----------
  { en: 'red',      ur: 'سرخ',     ar: 'أحمر',   emoji: '🔴' },
  { en: 'blue',     ur: 'نیلا',    ar: 'أزرق',   emoji: '🔵' },
  { en: 'green',    ur: 'ہرا',     ar: 'أخضر',   emoji: '🟢' },
  { en: 'yellow',   ur: 'پیلا',    ar: 'أصفر',   emoji: '🟡' },
  { en: 'orange',   ur: 'نارنجی',  ar: 'برتقالي', emoji: '🟠' },
  { en: 'purple',   ur: 'جامنی',   ar: 'بنفسجي', emoji: '🟣' },
  { en: 'pink',     ur: 'گلابی',   ar: 'وردي',   emoji: '🩷' },
  { en: 'brown',    ur: 'بھورا',   ar: 'بني',    emoji: '🟤' },
  { en: 'black',    ur: 'کالا',    ar: 'أسود',   emoji: '⚫' },
  { en: 'white',    ur: 'سفید',    ar: 'أبيض',   emoji: '⚪' },
  { en: 'gray',     ur: 'سرمئی',   ar: 'رمادي',  emoji: '⚫' },
  { en: 'gold',     ur: 'سونا',    ar: 'ذهبي',   emoji: '🟡' },
  { en: 'silver',   ur: 'چاندی',   ar: 'فضي',    emoji: '⚪' },
  { en: 'rainbow',  ur: 'قوس قزح', ar: 'قوس قزح', emoji: '🌈' },
  { en: 'cream',    ur: 'کریمی',   ar: 'كريمي',  emoji: '⚪' },

  // ---------- FAMILY / PEOPLE (25) ----------
  { en: 'mom',      ur: 'امی',     ar: 'أم',     emoji: '👩' },
  { en: 'dad',      ur: 'ابو',     ar: 'أب',     emoji: '👨' },
  { en: 'baby',     ur: 'بچہ',     ar: 'طفل',    emoji: '👶' },
  { en: 'boy',      ur: 'لڑکا',    ar: 'ولد',    emoji: '👦' },
  { en: 'girl',     ur: 'لڑکی',    ar: 'فتاة',   emoji: '👧' },
  { en: 'man',      ur: 'آدمی',    ar: 'رجل',    emoji: '👨' },
  { en: 'woman',    ur: 'عورت',    ar: 'امرأة',  emoji: '👩' },
  { en: 'kid',      ur: 'بچہ',     ar: 'طفل',    emoji: '🧒' },
  { en: 'family',   ur: 'خاندان',  ar: 'عائلة',  emoji: '👨‍👩‍👧' },
  { en: 'friend',   ur: 'دوست',    ar: 'صديق',   emoji: '🤝' },
  { en: 'brother',  ur: 'بھائی',   ar: 'أخ',     emoji: '👦' },
  { en: 'sister',   ur: 'بہن',     ar: 'أخت',    emoji: '👧' },
  { en: 'uncle',    ur: 'چچا',     ar: 'عم',     emoji: '👨' },
  { en: 'aunt',     ur: 'خالہ',    ar: 'خالة',   emoji: '👩' },
  { en: 'grandma',  ur: 'دادی',    ar: 'جدة',    emoji: '👵' },
  { en: 'grandpa',  ur: 'دادا',    ar: 'جد',     emoji: '👴' },
  { en: 'cousin',   ur: 'کزن',     ar: 'ابن عم', emoji: '🧑' },
  { en: 'teacher',  ur: 'استاد',   ar: 'معلم',   emoji: '👨‍🏫' },
  { en: 'doctor',   ur: 'ڈاکٹر',   ar: 'طبيب',   emoji: '👨‍⚕️' },
  { en: 'nurse',    ur: 'نرس',     ar: 'ممرضة',  emoji: '👩‍⚕️' },
  { en: 'police',   ur: 'پولیس',   ar: 'شرطة',   emoji: '👮' },
  { en: 'farmer',   ur: 'کسان',    ar: 'مزارع',  emoji: '👨‍🌾' },
  { en: 'cook',     ur: 'باورچی',  ar: 'طاهي',   emoji: '👨‍🍳' },
  { en: 'king',     ur: 'بادشاہ',  ar: 'ملك',    emoji: '🤴' },
  { en: 'queen',    ur: 'ملکہ',    ar: 'ملكة',   emoji: '👸' },

  // ---------- CLOTHING (25) ----------
  { en: 'shirt',    ur: 'قمیض',    ar: 'قميص',   emoji: '👕' },
  { en: 'pants',    ur: 'پتلون',   ar: 'بنطال',  emoji: '👖' },
  { en: 'shoe',     ur: 'جوتا',    ar: 'حذاء',   emoji: '👟' },
  { en: 'sock',     ur: 'موزہ',    ar: 'جورب',   emoji: '🧦' },
  { en: 'hat',      ur: 'ٹوپی',    ar: 'قبعة',   emoji: '🎩' },
  { en: 'cap',      ur: 'ٹوپی',    ar: 'كاب',    emoji: '🧢' },
  { en: 'coat',     ur: 'کوٹ',     ar: 'معطف',   emoji: '🧥' },
  { en: 'jacket',   ur: 'جیکٹ',    ar: 'سترة',   emoji: '🧥' },
  { en: 'dress',    ur: 'لباس',    ar: 'فستان',  emoji: '👗' },
  { en: 'skirt',    ur: 'اسکرٹ',   ar: 'تنورة',  emoji: '👗' },
  { en: 'shorts',   ur: 'نیکر',    ar: 'شورت',   emoji: '🩳' },
  { en: 'gloves',   ur: 'دستانے',  ar: 'قفازات', emoji: '🧤' },
  { en: 'scarf',    ur: 'مفلر',    ar: 'وشاح',   emoji: '🧣' },
  { en: 'boot',     ur: 'بوٹ',     ar: 'حذاء طويل', emoji: '👢' },
  { en: 'sandal',   ur: 'چپل',     ar: 'صندل',   emoji: '👡' },
  { en: 'tie',      ur: 'ٹائی',    ar: 'ربطة',   emoji: '👔' },
  { en: 'belt',     ur: 'بیلٹ',    ar: 'حزام',   emoji: '👖' },
  { en: 'bag',      ur: 'بیگ',     ar: 'حقيبة',  emoji: '👜' },
  { en: 'purse',    ur: 'بٹوہ',    ar: 'محفظة',  emoji: '👛' },
  { en: 'glasses',  ur: 'عینک',    ar: 'نظارات', emoji: '👓' },
  { en: 'crown',    ur: 'تاج',     ar: 'تاج',    emoji: '👑' },
  { en: 'ring',     ur: 'انگوٹھی', ar: 'خاتم',   emoji: '💍' },
  { en: 'watch',    ur: 'گھڑی',    ar: 'ساعة',   emoji: '⌚' },
  { en: 'umbrella', ur: 'چھتری',   ar: 'مظلة',   emoji: '☂️' },
  { en: 'pocket',   ur: 'جیب',     ar: 'جيب',    emoji: '👖' },

  // ---------- HOUSEHOLD / OBJECTS (60) ----------
  { en: 'bed',      ur: 'بستر',    ar: 'سرير',   emoji: '🛏️' },
  { en: 'chair',    ur: 'کرسی',    ar: 'كرسي',   emoji: '🪑' },
  { en: 'table',    ur: 'میز',     ar: 'طاولة',  emoji: '🪑' },
  { en: 'sofa',     ur: 'صوفہ',    ar: 'أريكة',  emoji: '🛋️' },
  { en: 'door',     ur: 'دروازہ',  ar: 'باب',    emoji: '🚪' },
  { en: 'window',   ur: 'کھڑکی',   ar: 'نافذة',  emoji: '🪟' },
  { en: 'wall',     ur: 'دیوار',   ar: 'جدار',   emoji: '🧱' },
  { en: 'roof',     ur: 'چھت',     ar: 'سقف',    emoji: '🏠' },
  { en: 'floor',    ur: 'فرش',     ar: 'أرضية',  emoji: '🟫' },
  { en: 'lamp',     ur: 'لیمپ',    ar: 'مصباح',  emoji: '💡' },
  { en: 'candle',   ur: 'موم بتی', ar: 'شمعة',   emoji: '🕯️' },
  { en: 'mirror',   ur: 'آئینہ',   ar: 'مرآة',   emoji: '🪞' },
  { en: 'clock',    ur: 'گھڑی',    ar: 'ساعة',   emoji: '🕰️' },
  { en: 'phone',    ur: 'فون',     ar: 'هاتف',   emoji: '📱' },
  { en: 'tv',       ur: 'ٹی وی',   ar: 'تلفاز',  emoji: '📺' },
  { en: 'radio',    ur: 'ریڈیو',   ar: 'راديو',  emoji: '📻' },
  { en: 'camera',   ur: 'کیمرا',   ar: 'كاميرا', emoji: '📷' },
  { en: 'computer', ur: 'کمپیوٹر', ar: 'حاسوب',  emoji: '💻' },
  { en: 'mouse',    ur: 'ماؤس',    ar: 'فأرة',   emoji: '🖱️' },
  { en: 'keyboard', ur: 'کی بورڈ', ar: 'لوحة مفاتيح', emoji: '⌨️' },
  { en: 'fan',      ur: 'پنکھا',   ar: 'مروحة',  emoji: '🌀' },
  { en: 'oven',     ur: 'تندور',   ar: 'فرن',    emoji: '🔥' },
  { en: 'fridge',   ur: 'فریج',    ar: 'ثلاجة',  emoji: '🧊' },
  { en: 'pot',      ur: 'برتن',    ar: 'وعاء',   emoji: '🍲' },
  { en: 'pan',      ur: 'کڑاہی',   ar: 'مقلاة',  emoji: '🍳' },
  { en: 'plate',    ur: 'پلیٹ',    ar: 'طبق',    emoji: '🍽️' },
  { en: 'bowl',     ur: 'پیالہ',   ar: 'وعاء',   emoji: '🥣' },
  { en: 'fork',     ur: 'کانٹا',   ar: 'شوكة',   emoji: '🍴' },
  { en: 'spoon',    ur: 'چمچ',     ar: 'ملعقة',  emoji: '🥄' },
  { en: 'knife',    ur: 'چاقو',    ar: 'سكين',   emoji: '🔪' },
  { en: 'glass',    ur: 'گلاس',    ar: 'كأس',    emoji: '🥛' },
  { en: 'mug',      ur: 'مگ',      ar: 'كوب',    emoji: '☕' },
  { en: 'kettle',   ur: 'کیتلی',   ar: 'إبريق',  emoji: '🫖' },
  { en: 'broom',    ur: 'جھاڑو',   ar: 'مكنسة',  emoji: '🧹' },
  { en: 'bucket',   ur: 'بالٹی',   ar: 'دلو',    emoji: '🪣' },
  { en: 'soap',     ur: 'صابن',    ar: 'صابون',  emoji: '🧼' },
  { en: 'towel',    ur: 'تولیہ',   ar: 'منشفة',  emoji: '🛁' },
  { en: 'brush',    ur: 'برش',     ar: 'فرشاة',  emoji: '🪥' },
  { en: 'comb',     ur: 'کنگھی',   ar: 'مشط',    emoji: '💇' },
  { en: 'toothbrush', ur: 'دانت برش', ar: 'فرشاة أسنان', emoji: '🪥' },
  { en: 'pillow',   ur: 'تکیہ',    ar: 'وسادة',  emoji: '🛏️' },
  { en: 'blanket',  ur: 'کمبل',    ar: 'بطانية', emoji: '🛏️' },
  { en: 'curtain',  ur: 'پردہ',    ar: 'ستارة',  emoji: '🪟' },
  { en: 'carpet',   ur: 'قالین',   ar: 'سجاد',   emoji: '🟫' },
  { en: 'box',      ur: 'ڈبہ',     ar: 'صندوق',  emoji: '📦' },
  { en: 'basket',   ur: 'ٹوکری',   ar: 'سلة',    emoji: '🧺' },
  { en: 'bag',      ur: 'تھیلا',   ar: 'كيس',    emoji: '🛍️' },
  { en: 'key',      ur: 'چابی',    ar: 'مفتاح',  emoji: '🔑' },
  { en: 'lock',     ur: 'تالا',    ar: 'قفل',    emoji: '🔒' },
  { en: 'rope',     ur: 'رسی',     ar: 'حبل',    emoji: '➰' },
  { en: 'chain',    ur: 'زنجیر',   ar: 'سلسلة',  emoji: '⛓️' },
  { en: 'nail',     ur: 'کیل',     ar: 'مسمار',  emoji: '🔩' },
  { en: 'hammer',   ur: 'ہتھوڑا',  ar: 'مطرقة',  emoji: '🔨' },
  { en: 'saw',      ur: 'آرا',     ar: 'منشار',  emoji: '🪚' },
  { en: 'wrench',   ur: 'پانہ',    ar: 'مفتاح ربط', emoji: '🔧' },
  { en: 'screw',    ur: 'پیچ',     ar: 'برغي',   emoji: '🔩' },
  { en: 'pen',      ur: 'قلم',     ar: 'قلم',    emoji: '🖊️' },
  { en: 'pencil',   ur: 'پنسل',    ar: 'قلم رصاص', emoji: '✏️' },
  { en: 'eraser',   ur: 'ربر',     ar: 'ممحاة',  emoji: '🩹' },
  { en: 'paper',    ur: 'کاغذ',    ar: 'ورق',    emoji: '📄' },

  // ---------- VEHICLES / TRANSPORT (25) ----------
  { en: 'car',      ur: 'گاڑی',    ar: 'سيارة',  emoji: '🚗' },
  { en: 'bus',      ur: 'بس',      ar: 'حافلة',  emoji: '🚌' },
  { en: 'truck',    ur: 'ٹرک',     ar: 'شاحنة',  emoji: '🚚' },
  { en: 'van',      ur: 'وین',     ar: 'شاحنة صغيرة', emoji: '🚐' },
  { en: 'taxi',     ur: 'ٹیکسی',   ar: 'سيارة أجرة', emoji: '🚕' },
  { en: 'bike',     ur: 'سائیکل',  ar: 'دراجة',  emoji: '🚲' },
  { en: 'motorcycle', ur: 'موٹرسائیکل', ar: 'دراجة نارية', emoji: '🏍️' },
  { en: 'train',    ur: 'ٹرین',    ar: 'قطار',   emoji: '🚂' },
  { en: 'tram',     ur: 'ٹرام',    ar: 'ترام',   emoji: '🚊' },
  { en: 'plane',    ur: 'ہوائی جہاز', ar: 'طائرة', emoji: '✈️' },
  { en: 'helicopter', ur: 'ہیلی کاپٹر', ar: 'هليكوبتر', emoji: '🚁' },
  { en: 'boat',     ur: 'کشتی',    ar: 'قارب',   emoji: '⛵' },
  { en: 'ship',     ur: 'جہاز',    ar: 'سفينة',  emoji: '🚢' },
  { en: 'rocket',   ur: 'راکٹ',    ar: 'صاروخ',  emoji: '🚀' },
  { en: 'tractor',  ur: 'ٹریکٹر',  ar: 'جرار',   emoji: '🚜' },
  { en: 'wagon',    ur: 'ویگن',    ar: 'عربة',   emoji: '🛻' },
  { en: 'wheel',    ur: 'پہیہ',    ar: 'عجلة',   emoji: '☸️' },
  { en: 'tire',     ur: 'ٹائر',    ar: 'إطار',   emoji: '🛞' },
  { en: 'road',     ur: 'سڑک',     ar: 'طريق',   emoji: '🛣️' },
  { en: 'bridge',   ur: 'پل',      ar: 'جسر',    emoji: '🌉' },
  { en: 'station',  ur: 'اسٹیشن',  ar: 'محطة',   emoji: '🚉' },
  { en: 'airport',  ur: 'ہوائی اڈہ', ar: 'مطار', emoji: '🛫' },
  { en: 'sled',     ur: 'سلیج',    ar: 'مزلجة',  emoji: '🛷' },
  { en: 'skate',    ur: 'سکیٹ',    ar: 'تزلج',   emoji: '⛸️' },
  { en: 'scooter',  ur: 'سکوٹر',   ar: 'سكوتر',  emoji: '🛴' },

  // ---------- WEATHER / NATURE (40) ----------
  { en: 'sun',      ur: 'سورج',    ar: 'شمس',    emoji: '☀️' },
  { en: 'moon',     ur: 'چاند',    ar: 'قمر',    emoji: '🌙' },
  { en: 'star',     ur: 'ستارہ',   ar: 'نجمة',   emoji: '⭐' },
  { en: 'sky',      ur: 'آسمان',   ar: 'سماء',   emoji: '🌤️' },
  { en: 'cloud',    ur: 'بادل',    ar: 'سحابة',  emoji: '☁️' },
  { en: 'rain',     ur: 'بارش',    ar: 'مطر',    emoji: '🌧️' },
  { en: 'snow',     ur: 'برف',     ar: 'ثلج',    emoji: '❄️' },
  { en: 'wind',     ur: 'ہوا',     ar: 'ريح',    emoji: '💨' },
  { en: 'storm',    ur: 'طوفان',   ar: 'عاصفة',  emoji: '⛈️' },
  { en: 'thunder',  ur: 'گرج',     ar: 'رعد',    emoji: '⚡' },
  { en: 'lightning', ur: 'بجلی',   ar: 'برق',    emoji: '⚡' },
  { en: 'rainbow',  ur: 'قوس قزح', ar: 'قوس قزح', emoji: '🌈' },
  { en: 'fog',      ur: 'دھند',    ar: 'ضباب',   emoji: '🌫️' },
  { en: 'ice',      ur: 'برف',     ar: 'ثلج',    emoji: '🧊' },
  { en: 'fire',     ur: 'آگ',      ar: 'نار',    emoji: '🔥' },
  { en: 'tree',     ur: 'درخت',    ar: 'شجرة',   emoji: '🌳' },
  { en: 'leaf',     ur: 'پتا',     ar: 'ورقة',   emoji: '🍃' },
  { en: 'flower',   ur: 'پھول',    ar: 'زهرة',   emoji: '🌸' },
  { en: 'rose',     ur: 'گلاب',    ar: 'وردة',   emoji: '🌹' },
  { en: 'tulip',    ur: 'گل لالہ', ar: 'توليب',  emoji: '🌷' },
  { en: 'sunflower', ur: 'سورج مکھی', ar: 'دوار الشمس', emoji: '🌻' },
  { en: 'grass',    ur: 'گھاس',    ar: 'عشب',    emoji: '🌿' },
  { en: 'cactus',   ur: 'کیکٹس',   ar: 'صبار',   emoji: '🌵' },
  { en: 'mountain', ur: 'پہاڑ',    ar: 'جبل',    emoji: '⛰️' },
  { en: 'hill',     ur: 'پہاڑی',   ar: 'تل',     emoji: '🌄' },
  { en: 'rock',     ur: 'پتھر',    ar: 'صخرة',   emoji: '🪨' },
  { en: 'stone',    ur: 'پتھر',    ar: 'حجر',    emoji: '🪨' },
  { en: 'sand',     ur: 'ریت',     ar: 'رمل',    emoji: '🏖️' },
  { en: 'beach',    ur: 'ساحل',    ar: 'شاطئ',   emoji: '🏖️' },
  { en: 'sea',      ur: 'سمندر',   ar: 'بحر',    emoji: '🌊' },
  { en: 'ocean',    ur: 'سمندر',   ar: 'محيط',   emoji: '🌊' },
  { en: 'wave',     ur: 'لہر',     ar: 'موجة',   emoji: '🌊' },
  { en: 'lake',     ur: 'جھیل',    ar: 'بحيرة',  emoji: '🏞️' },
  { en: 'river',    ur: 'دریا',    ar: 'نهر',    emoji: '🏞️' },
  { en: 'island',   ur: 'جزیرہ',   ar: 'جزيرة',  emoji: '🏝️' },
  { en: 'forest',   ur: 'جنگل',    ar: 'غابة',   emoji: '🌲' },
  { en: 'desert',   ur: 'صحرا',    ar: 'صحراء',  emoji: '🏜️' },
  { en: 'volcano',  ur: 'آتش فشاں', ar: 'بركان', emoji: '🌋' },
  { en: 'cave',     ur: 'غار',     ar: 'كهف',    emoji: '🏔️' },
  { en: 'planet',   ur: 'سیارہ',   ar: 'كوكب',   emoji: '🪐' },

  // ---------- BUILDINGS / PLACES (25) ----------
  { en: 'house',    ur: 'گھر',     ar: 'بيت',    emoji: '🏠' },
  { en: 'home',     ur: 'گھر',     ar: 'منزل',   emoji: '🏡' },
  { en: 'school',   ur: 'سکول',    ar: 'مدرسة',  emoji: '🏫' },
  { en: 'shop',     ur: 'دکان',    ar: 'متجر',   emoji: '🏬' },
  { en: 'store',    ur: 'سٹور',    ar: 'محل',    emoji: '🏪' },
  { en: 'hospital', ur: 'ہسپتال',  ar: 'مستشفى', emoji: '🏥' },
  { en: 'church',   ur: 'گرجا',    ar: 'كنيسة',  emoji: '⛪' },
  { en: 'mosque',   ur: 'مسجد',    ar: 'مسجد',   emoji: '🕌' },
  { en: 'temple',   ur: 'مندر',    ar: 'معبد',   emoji: '🛕' },
  { en: 'castle',   ur: 'قلعہ',    ar: 'قلعة',   emoji: '🏰' },
  { en: 'palace',   ur: 'محل',     ar: 'قصر',    emoji: '🏯' },
  { en: 'tent',     ur: 'خیمہ',    ar: 'خيمة',   emoji: '⛺' },
  { en: 'hut',      ur: 'جھونپڑی', ar: 'كوخ',    emoji: '🛖' },
  { en: 'barn',     ur: 'گودام',   ar: 'حظيرة',  emoji: '🏚️' },
  { en: 'park',     ur: 'پارک',    ar: 'حديقة',  emoji: '🌳' },
  { en: 'garden',   ur: 'باغ',     ar: 'حديقة',  emoji: '🌷' },
  { en: 'zoo',      ur: 'چڑیا گھر', ar: 'حديقة حيوان', emoji: '🦒' },
  { en: 'farm',     ur: 'فارم',    ar: 'مزرعة',  emoji: '🚜' },
  { en: 'office',   ur: 'دفتر',    ar: 'مكتب',   emoji: '🏢' },
  { en: 'bank',     ur: 'بینک',    ar: 'بنك',    emoji: '🏦' },
  { en: 'library',  ur: 'لائبریری', ar: 'مكتبة', emoji: '📚' },
  { en: 'pool',     ur: 'تالاب',   ar: 'بركة',   emoji: '🏊' },
  { en: 'gym',      ur: 'جم',      ar: 'صالة',   emoji: '🏋️' },
  { en: 'cafe',     ur: 'کیفے',    ar: 'مقهى',   emoji: '☕' },
  { en: 'market',   ur: 'بازار',   ar: 'سوق',    emoji: '🏪' },

  // ---------- SCHOOL / STATIONERY (20) ----------
  { en: 'book',     ur: 'کتاب',    ar: 'كتاب',   emoji: '📖' },
  { en: 'page',     ur: 'صفحہ',    ar: 'صفحة',   emoji: '📄' },
  { en: 'note',     ur: 'نوٹ',     ar: 'مذكرة',  emoji: '📝' },
  { en: 'crayon',   ur: 'کریون',   ar: 'قلم تلوين', emoji: '🖍️' },
  { en: 'marker',   ur: 'مارکر',   ar: 'قلم تخطيط', emoji: '🖊️' },
  { en: 'ruler',    ur: 'رولر',    ar: 'مسطرة',  emoji: '📏' },
  { en: 'scissors', ur: 'قینچی',   ar: 'مقص',    emoji: '✂️' },
  { en: 'glue',     ur: 'گوند',    ar: 'صمغ',    emoji: '🩹' },
  { en: 'tape',     ur: 'ٹیپ',     ar: 'شريط',   emoji: '📼' },
  { en: 'globe',    ur: 'گلوب',    ar: 'كرة أرضية', emoji: '🌍' },
  { en: 'map',      ur: 'نقشہ',    ar: 'خريطة',  emoji: '🗺️' },
  { en: 'flag',     ur: 'جھنڈا',   ar: 'علم',    emoji: '🚩' },
  { en: 'desk',     ur: 'ڈیسک',    ar: 'مكتب',   emoji: '🪑' },
  { en: 'board',    ur: 'بورڈ',    ar: 'لوحة',   emoji: '📋' },
  { en: 'chalk',    ur: 'چاک',     ar: 'طباشير', emoji: '✏️' },
  { en: 'bell',     ur: 'گھنٹی',   ar: 'جرس',    emoji: '🔔' },
  { en: 'art',      ur: 'فن',      ar: 'فن',     emoji: '🎨' },
  { en: 'paint',    ur: 'رنگ',     ar: 'دهان',   emoji: '🎨' },
  { en: 'class',    ur: 'کلاس',    ar: 'فصل',    emoji: '👨‍🏫' },
  { en: 'test',     ur: 'امتحان',  ar: 'اختبار', emoji: '📝' },

  // ---------- TOYS / GAMES (20) ----------
  { en: 'ball',     ur: 'گیند',    ar: 'كرة',    emoji: '⚽' },
  { en: 'doll',     ur: 'گڑیا',    ar: 'دمية',   emoji: '🪆' },
  { en: 'kite',     ur: 'پتنگ',    ar: 'طائرة ورقية', emoji: '🪁' },
  { en: 'block',    ur: 'بلاک',    ar: 'مكعب',   emoji: '🟦' },
  { en: 'puzzle',   ur: 'پہیلی',   ar: 'لغز',    emoji: '🧩' },
  { en: 'lego',     ur: 'لیگو',    ar: 'ليغو',   emoji: '🧱' },
  { en: 'teddy',    ur: 'ٹیڈی',    ar: 'دب دمية', emoji: '🧸' },
  { en: 'swing',    ur: 'جھولا',   ar: 'أرجوحة', emoji: '🛝' },
  { en: 'slide',    ur: 'سلائڈ',   ar: 'منزلق',  emoji: '🛝' },
  { en: 'top',      ur: 'لٹو',     ar: 'بلبل',   emoji: '🪀' },
  { en: 'yoyo',     ur: 'یویو',    ar: 'يويو',   emoji: '🪀' },
  { en: 'drum',     ur: 'ڈرم',     ar: 'طبل',    emoji: '🥁' },
  { en: 'guitar',   ur: 'گٹار',    ar: 'غيتار',  emoji: '🎸' },
  { en: 'piano',    ur: 'پیانو',   ar: 'بيانو',  emoji: '🎹' },
  { en: 'flute',    ur: 'بانسری',  ar: 'ناي',    emoji: '🎶' },
  { en: 'violin',   ur: 'وائلن',   ar: 'كمان',   emoji: '🎻' },
  { en: 'trumpet',  ur: 'تری',     ar: 'بوق',    emoji: '🎺' },
  { en: 'whistle',  ur: 'سیٹی',    ar: 'صافرة',  emoji: '🎶' },
  { en: 'balloon',  ur: 'غبارہ',   ar: 'بالون',  emoji: '🎈' },
  { en: 'gift',     ur: 'تحفہ',    ar: 'هدية',   emoji: '🎁' },

  // ---------- SPORTS / ACTIVITIES (15) ----------
  { en: 'soccer',   ur: 'فٹبال',   ar: 'كرة القدم', emoji: '⚽' },
  { en: 'tennis',   ur: 'ٹینس',    ar: 'تنس',    emoji: '🎾' },
  { en: 'basketball', ur: 'باسکٹ بال', ar: 'كرة سلة', emoji: '🏀' },
  { en: 'cricket',  ur: 'کرکٹ',    ar: 'كريكيت', emoji: '🏏' },
  { en: 'baseball', ur: 'بیس بال', ar: 'بيسبول', emoji: '⚾' },
  { en: 'golf',     ur: 'گالف',    ar: 'غولف',   emoji: '⛳' },
  { en: 'hockey',   ur: 'ہاکی',    ar: 'هوكي',   emoji: '🏑' },
  { en: 'swim',     ur: 'تیرنا',   ar: 'سباحة',  emoji: '🏊' },
  { en: 'run',      ur: 'دوڑنا',   ar: 'يجري',   emoji: '🏃' },
  { en: 'jump',     ur: 'کودنا',   ar: 'يقفز',   emoji: '🤸' },
  { en: 'skate',    ur: 'سکیٹ',    ar: 'تزلج',   emoji: '⛸️' },
  { en: 'ski',      ur: 'سکی',     ar: 'تزلج',   emoji: '⛷️' },
  { en: 'box',      ur: 'باکسنگ',  ar: 'ملاكمة', emoji: '🥊' },
  { en: 'dance',    ur: 'ناچ',     ar: 'رقص',    emoji: '💃' },
  { en: 'yoga',     ur: 'یوگا',    ar: 'يوغا',   emoji: '🧘' },

  // ---------- VERBS — simple actions (30) ----------
  { en: 'eat',      ur: 'کھانا',   ar: 'يأكل',   emoji: '🍽️' },
  { en: 'drink',    ur: 'پینا',    ar: 'يشرب',   emoji: '🥤' },
  { en: 'sleep',    ur: 'سونا',    ar: 'ينام',   emoji: '😴' },
  { en: 'wake',     ur: 'جاگنا',   ar: 'يستيقظ', emoji: '⏰' },
  { en: 'walk',     ur: 'چلنا',    ar: 'يمشي',   emoji: '🚶' },
  { en: 'sit',      ur: 'بیٹھنا',  ar: 'يجلس',   emoji: '🪑' },
  { en: 'stand',    ur: 'کھڑا ہونا', ar: 'يقف',  emoji: '🧍' },
  { en: 'sing',     ur: 'گانا',    ar: 'يغني',   emoji: '🎤' },
  { en: 'play',     ur: 'کھیلنا',  ar: 'يلعب',   emoji: '🎮' },
  { en: 'read',     ur: 'پڑھنا',   ar: 'يقرأ',   emoji: '📖' },
  { en: 'write',    ur: 'لکھنا',   ar: 'يكتب',   emoji: '✍️' },
  { en: 'draw',     ur: 'ڈرائنگ',  ar: 'يرسم',   emoji: '🎨' },
  { en: 'wash',     ur: 'دھونا',   ar: 'يغسل',   emoji: '🧼' },
  { en: 'cook',     ur: 'پکانا',   ar: 'يطبخ',   emoji: '👨‍🍳' },
  { en: 'clean',    ur: 'صاف کرنا', ar: 'ينظف',  emoji: '🧹' },
  { en: 'open',     ur: 'کھولنا',  ar: 'يفتح',   emoji: '🔓' },
  { en: 'close',    ur: 'بند کرنا', ar: 'يغلق',  emoji: '🔒' },
  { en: 'push',     ur: 'دھکیلنا', ar: 'يدفع',   emoji: '👉' },
  { en: 'pull',     ur: 'کھینچنا', ar: 'يسحب',   emoji: '👈' },
  { en: 'cry',      ur: 'رونا',    ar: 'يبكي',   emoji: '😭' },
  { en: 'laugh',    ur: 'ہنسنا',   ar: 'يضحك',   emoji: '😂' },
  { en: 'smile',    ur: 'مسکرانا', ar: 'يبتسم',  emoji: '😊' },
  { en: 'kiss',     ur: 'بوسہ',    ar: 'قبلة',   emoji: '💋' },
  { en: 'hug',      ur: 'گلے لگانا', ar: 'يعانق', emoji: '🤗' },
  { en: 'help',     ur: 'مدد',     ar: 'يساعد',  emoji: '🤝' },
  { en: 'give',     ur: 'دینا',    ar: 'يعطي',   emoji: '🤲' },
  { en: 'take',     ur: 'لینا',    ar: 'يأخذ',   emoji: '🤲' },
  { en: 'wait',     ur: 'انتظار',  ar: 'ينتظر',  emoji: '⏳' },
  { en: 'go',       ur: 'جانا',    ar: 'يذهب',   emoji: '🚶' },
  { en: 'come',     ur: 'آنا',     ar: 'يأتي',   emoji: '🚶' },

  // ---------- ADJECTIVES — simple (20) ----------
  { en: 'big',      ur: 'بڑا',     ar: 'كبير',   emoji: '🐘' },
  { en: 'small',    ur: 'چھوٹا',   ar: 'صغير',   emoji: '🐭' },
  { en: 'hot',      ur: 'گرم',     ar: 'حار',    emoji: '🔥' },
  { en: 'cold',     ur: 'ٹھنڈا',   ar: 'بارد',   emoji: '🥶' },
  { en: 'warm',     ur: 'گرم',     ar: 'دافئ',   emoji: '☀️' },
  { en: 'wet',      ur: 'گیلا',    ar: 'مبلل',   emoji: '💧' },
  { en: 'dry',      ur: 'خشک',     ar: 'جاف',    emoji: '🏜️' },
  { en: 'fast',     ur: 'تیز',     ar: 'سريع',   emoji: '🏃' },
  { en: 'slow',     ur: 'سست',     ar: 'بطيء',   emoji: '🐌' },
  { en: 'high',     ur: 'اونچا',   ar: 'عالي',   emoji: '⬆️' },
  { en: 'low',      ur: 'نیچا',    ar: 'منخفض',  emoji: '⬇️' },
  { en: 'happy',    ur: 'خوش',     ar: 'سعيد',   emoji: '😊' },
  { en: 'sad',      ur: 'اداس',    ar: 'حزين',   emoji: '😢' },
  { en: 'angry',    ur: 'غصہ',     ar: 'غاضب',   emoji: '😠' },
  { en: 'tired',    ur: 'تھکا',    ar: 'متعب',   emoji: '😴' },
  { en: 'sweet',    ur: 'میٹھا',   ar: 'حلو',    emoji: '🍬' },
  { en: 'sour',     ur: 'کھٹا',    ar: 'حامض',   emoji: '🍋' },
  { en: 'soft',     ur: 'نرم',     ar: 'ناعم',   emoji: '☁️' },
  { en: 'hard',     ur: 'سخت',     ar: 'صلب',    emoji: '🪨' },
  { en: 'clean',    ur: 'صاف',     ar: 'نظيف',   emoji: '✨' },

  // ---------- NUMBERS / SHAPES / TIME (25) ----------
  { en: 'one',      ur: 'ایک',     ar: 'واحد',   emoji: '1️⃣' },
  { en: 'two',      ur: 'دو',      ar: 'اثنان',  emoji: '2️⃣' },
  { en: 'three',    ur: 'تین',     ar: 'ثلاثة',  emoji: '3️⃣' },
  { en: 'four',     ur: 'چار',     ar: 'أربعة',  emoji: '4️⃣' },
  { en: 'five',     ur: 'پانچ',    ar: 'خمسة',   emoji: '5️⃣' },
  { en: 'six',      ur: 'چھ',      ar: 'ستة',    emoji: '6️⃣' },
  { en: 'seven',    ur: 'سات',     ar: 'سبعة',   emoji: '7️⃣' },
  { en: 'eight',    ur: 'آٹھ',     ar: 'ثمانية', emoji: '8️⃣' },
  { en: 'nine',     ur: 'نو',      ar: 'تسعة',   emoji: '9️⃣' },
  { en: 'ten',      ur: 'دس',      ar: 'عشرة',   emoji: '🔟' },
  { en: 'circle',   ur: 'دائرہ',   ar: 'دائرة',  emoji: '⭕' },
  { en: 'square',   ur: 'مربع',    ar: 'مربع',   emoji: '🟥' },
  { en: 'triangle', ur: 'تکونا',   ar: 'مثلث',   emoji: '🔺' },
  { en: 'star',     ur: 'ستارہ',   ar: 'نجمة',   emoji: '⭐' },
  { en: 'heart',    ur: 'دل',      ar: 'قلب',    emoji: '❤️' },
  { en: 'diamond',  ur: 'ہیرا',    ar: 'ماس',    emoji: '🔷' },
  { en: 'day',      ur: 'دن',      ar: 'يوم',    emoji: '☀️' },
  { en: 'night',    ur: 'رات',     ar: 'ليل',    emoji: '🌙' },
  { en: 'morning',  ur: 'صبح',     ar: 'صباح',   emoji: '🌅' },
  { en: 'evening',  ur: 'شام',     ar: 'مساء',   emoji: '🌆' },
  { en: 'today',    ur: 'آج',      ar: 'اليوم',  emoji: '📅' },
  { en: 'week',     ur: 'ہفتہ',    ar: 'أسبوع',  emoji: '📅' },
  { en: 'month',    ur: 'مہینہ',   ar: 'شهر',    emoji: '📅' },
  { en: 'year',     ur: 'سال',     ar: 'سنة',    emoji: '📅' },
  { en: 'birthday', ur: 'سالگرہ',  ar: 'عيد ميلاد', emoji: '🎂' }
];

export function pickWordsByLength(min, max) {
  return DAILY_WORDS.filter(w => w.en.length >= min && w.en.length <= max);
}

// Stable pick for any given date — same calendar day always returns the same word.
export function dailyWord(date = new Date()) {
  const d = new Date(date.getFullYear(), date.getMonth(), date.getDate());
  // Days since epoch
  const dayIndex = Math.floor(d.getTime() / 86400000);
  return DAILY_WORDS[dayIndex % DAILY_WORDS.length];
}
