// Auto-generated by scripts/fetch_images.py.
// Set of slugs that have a curated photo at /public/words/{slug}.jpg.
// engine.visualFor() reads this to decide image vs emoji.
// To regenerate: bash + python3 scripts/fetch_images.py, then run:
//   python3 -c "import os;[print(repr(f.replace('.jpg','')),end=', ')for f in sorted(os.listdir('public/words'))if f.endswith('.jpg')]"

export const WORDS_WITH_IMAGES = new Set([
  'apple',
  'banana',
  'bee',
  'bird',
  'butterfly',
  'camel',
  'cat',
  'cow',
  'dog',
  'duck',
  'elephant',
  'fish',
  'frog',
  'giraffe',
  'goat',
  'grapes',
  'horse',
  'lion',
  'mango',
  'monkey',
  'orange',
  'owl',
  'parrot',
  'peacock',
  'pineapple',
  'rabbit',
  'sheep',
  'snake',
  'strawberry',
  'tiger',
  'watermelon',
  'zebra'
]);
